#!/bin/sh

REL="$(dirname "$0")"

JAM="jazz/jam"

bootstrap_init () {
	cd "$REL"
    git submodule init
}

bootstrap_update () {
	cd "$REL"
    git submodule update
}

bootstrap () {
    (bootstrap_init) &&
    (bootstrap_update)
}

bootstrap_dispatch () {
    case "$1" in
	"init" )
	    bootstrap_init
	    ;;
	"update" )
	    bootstrap_update
	    ;;
	"" )
	    bootstrap
	    ;;
	* )
	    echo "Unknown bootstrap option : $1"
	    return 1
	    ;;
    esac
}

case "$1" in
	"bootstrap" )
		bootstrap_dispatch $2
		exit
		;;
esac

if [ ! -f "$JAM" ]; then
	bootstrap
fi

if [ ! -f "$JAM" ]; then
	echo "Unable to find jazz/jam"
	exit 1
fi

exec "$JAM" "$@"
