#!/bin/sh

REL="$(dirname "$0")"

JAZZ="$REL/jazz"
JAZ="$JAZZ/jaz"

display_module_info () {
    echo "$1"
    if [ -d "$2" ]; then
	cd "$2" &&
	git log -1
    fi
}

display_info () {
    (display_module_info "Jedi" "$REL")
    echo
    (display_module_info "Jazz" "$JAZZ")
}

case "$1" in
	"info" )
		display_info
		exit
		;;
esac

if [ ! -f "$JAZ" ]; then
	echo "Unable to find jazz/jaz"
	exit 1
fi

exec "$JAZ" "$@"
